const actionsType = {
    AUTH_START: "AUTH_START",
    AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
    AUTH_FAIL: "AUTH_FAIL",
    AUTH_LOGOUT: "AUTH_LOGOUT",

    PETS_START: "PETS_START",
    PETS_SUCCESS: "PETS_SUCCESS",
    GET_PET_BY_ID: "GET_PET_BY_ID",
    PETS_FAIL: "PETS_FAIL",

    PRODUCTS_START: "PRODUCTS_START",
    PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
    GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
    PRODUCTS_FAIL: "PRODUCTS_FAIL",
};

export default actionsType;
